"use client";
import Link from "next/link";
import type { Route } from "next";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button, ErrorState, Skeleton } from "@/components/public/ui";
import { userAuthFetch } from "@/lib/user-auth/client";
import { useProtectedAction } from "@/features/user-auth/protected-action-context";
import { normalizeComment } from "@/features/social/mapper";
import type { Comment, PublicError } from "@/features/social/types";
async function comments(postId: string) { const response = await fetch(`/api/public/posts/${postId}/comments?limit=50`, { cache: "no-store" }); if (!response.ok) throw await response.json() as PublicError; return response.json() as Promise<Comment[]>; }
export function Comments({ postId }: { postId: string }) { const protectedAction = useProtectedAction(); const queryClient = useQueryClient(); const [draft, setDraft] = useState(""); const query = useQuery({ queryKey: ["public", "comments", postId], queryFn: () => comments(postId), retry: false }); const create = useMutation({ mutationFn: (body: string) => userAuthFetch(`/api/user/posts/${postId}/comments`, { method: "POST", body: JSON.stringify({ body }), headers: { "Idempotency-Key": crypto.randomUUID() } }), onSuccess: () => { setDraft(""); void queryClient.invalidateQueries({ queryKey: ["public", "comments", postId] }); } }); const submit = () => { const body = normalizeComment(draft); if (!body) return; protectedAction({ reason: "Connectez-vous pour commenter", level: "L2", run: () => create.mutate(body) }); }; return <section className="yy-comments" aria-labelledby="comments-title"><h2 id="comments-title">Commentaires</h2>{query.isPending ? <Skeleton /> : query.isError ? <ErrorState title="Commentaires indisponibles" message={(query.error as unknown as PublicError).message ?? "Les commentaires ne sont pas disponibles."} /> : query.data?.length ? <ol>{query.data.map((comment) => <li key={comment.id}><Link href={`/users/${comment.authorId}` as Route}>Auteur</Link><time dateTime={comment.createdAt}>{new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium" }).format(new Date(comment.createdAt))}</time><p>{comment.body}</p></li>)}</ol> : <p className="yy-comments-empty">Aucun commentaire public.</p>}<label htmlFor={`comment-${postId}`}>Ajouter un commentaire</label><textarea id={`comment-${postId}`} value={draft} onChange={(event) => setDraft(event.target.value)} maxLength={2000} placeholder="Partagez votre avis" /><Button type="button" disabled={!normalizeComment(draft) || create.isPending} onClick={submit}>Commenter</Button>{create.isError ? <p role="alert">Le commentaire n’a pas pu être envoyé.</p> : null}</section>; }
