"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Heart, Share2, UserRound } from "lucide-react";
import { Button, ErrorState, Skeleton } from "@/components/public/ui";
import { userAuthFetch } from "@/lib/user-auth/client";
import { useProtectedAction } from "@/features/user-auth/protected-action-context";
import type { MyProfile, PublicError, PublicProfile } from "@/features/social/types";
async function publicProfile(id: string) { const response = await fetch(`/api/public/users/${id}`, { cache: "no-store" }); if (!response.ok) throw await response.json() as PublicError; return response.json() as Promise<PublicProfile>; }
async function ownProfile() { return userAuthFetch<MyProfile>("/api/user/profile"); }
export function PublicProfilePage({ id }: { id: string }) { const protectedAction = useProtectedAction(); const client = useQueryClient(); const query = useQuery({ queryKey: ["public", "profile", id], queryFn: () => publicProfile(id), retry: false }); const follow = useMutation({ mutationFn: (active: boolean) => userAuthFetch<void>(`/api/user/social/${id}/follow`, { method: active ? "DELETE" : "POST" }), onSuccess: () => void client.invalidateQueries({ queryKey: ["public", "profile", id] }) }); if (query.isPending) return <div className="yy-profile"><Skeleton /></div>; if (query.isError || !query.data) return <ErrorState title="Profil indisponible" message={(query.error as unknown as PublicError)?.message ?? "Ce profil public est introuvable."} />; const profile = query.data; return <article className="yy-profile"><header><div className="yy-profile-avatar">{profile.avatarUrl ? <img src={profile.avatarUrl} alt="" /> : <UserRound aria-hidden="true" />}</div><div><p className="yy-kicker">Profil public</p><h1>{profile.displayName}</h1>{profile.bio ? <p>{profile.bio}</p> : null}{profile.language ? <p>{profile.language}</p> : null}</div></header><div className="yy-profile-actions"><Button type="button" aria-pressed={false} disabled={follow.isPending} onClick={() => protectedAction({ reason: "Connectez-vous pour suivre ce profil", level: "L1", intent: { type: "FOLLOW", resourceType: "profile", resourceId: id }, run: () => follow.mutate(false) })}><Heart aria-hidden="true" />Suivre</Button><Button type="button" onClick={() => { const url = window.location.href; if (navigator.share) void navigator.share({ title: profile.displayName, url }); else void navigator.clipboard?.writeText(url); }}><Share2 aria-hidden="true" />Partager</Button></div><p className="yy-profile-note">Les abonnements, compteurs et publications de profil ne sont pas exposés publiquement par les contrats actuels.</p></article>; }
export function OwnProfilePage() { const query = useQuery({ queryKey: ["user", "profile"], queryFn: ownProfile, retry: false }); if (query.isPending) return <div className="yy-profile"><Skeleton /></div>; if (query.isError || !query.data) return <ErrorState title="Profil indisponible" message="Votre profil ne peut pas être chargé." />; const profile = query.data; return <article className="yy-profile"><header><div className="yy-profile-avatar">{profile.avatarUrl ? <img src={profile.avatarUrl} alt="" /> : <UserRound aria-hidden="true" />}</div><div><p className="yy-kicker">Mon profil</p><h1>{profile.displayName}</h1>{profile.bio ? <p>{profile.bio}</p> : null}</div></header><p className="yy-profile-note">Vos préférences privées restent accessibles uniquement depuis les paramètres du compte.</p></article>; }
