"use client";
import { useState, type FormEvent } from "react";
import Link from "next/link";
import type { Route } from "next";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BriefcaseBusiness, CalendarCheck, MessageCircle, Pencil, Send } from "lucide-react";
import { Button, EmptyState, ErrorState, Skeleton } from "@/components/public/ui";
import { partnerPortalApi } from "@/features/partner-portal/api";
import { businessTypes, type PartnerInput, type PartnerProfile } from "@/features/partner-portal/types";

const empty: PartnerInput = { legalName: "", tradeName: null, businessType: "INDIVIDUAL", registrationNumber: null, taxId: null, contactEmail: "", contactPhone: null, websiteUrl: null, description: null, primaryCountryCode: null, operatingCountries: [] };
const editable = (profile: PartnerProfile): PartnerInput => ({ legalName: profile.legalName, tradeName: profile.tradeName, businessType: profile.businessType, registrationNumber: profile.registrationNumber, taxId: profile.taxId, contactEmail: profile.contactEmail, contactPhone: profile.contactPhone, websiteUrl: profile.websiteUrl, description: profile.description, primaryCountryCode: profile.primaryCountryCode, operatingCountries: profile.operatingCountries });

export function PartnerPortalPage() {
  const query = useQuery({ queryKey: ["user", "partner", "status"], queryFn: partnerPortalApi.status, retry: false });
  if (query.isPending) return <div className="yy-partner"><Skeleton /><Skeleton /></div>;
  if (query.isError || !query.data) return <ErrorState title="Espace partenaire indisponible" message="Votre statut partenaire ne peut pas être vérifié." />;
  const status = query.data;
  if (status.state === "NOT_PARTNER") return <PartnerForm title="Devenir partenaire" initial={empty} mode="create" />;
  if (!status.profile) return <EmptyState title="Profil introuvable" message="Aucun profil partenaire n’est disponible." />;
  if (!status.canAccessDashboard) return <ApplicationState profile={status.profile} canEdit={status.canEdit} canSubmit={status.canSubmit} />;
  return <section className="yy-partner"><header><p className="yy-kicker">Espace professionnel</p><h1>{status.profile.tradeName ?? status.profile.legalName}</h1><p>Gérez votre activité dans le périmètre autorisé par votre profil partenaire.</p></header><div className="yy-partner-kpis"><article><strong>{status.profile.status}</strong><span>Statut vérifié</span></article><article><strong>{status.profile.businessType}</strong><span>Type d’activité</span></article><article><strong>{status.profile.operatingCountries.length}</strong><span>Pays d’activité</span></article></div><div className="yy-partner-grid"><Link href={"/partner/profile" as Route}><Pencil aria-hidden="true" /><strong>Profil professionnel</strong><span>Consulter vos informations vérifiées.</span></Link><Link href={"/partner/bookings" as Route}><CalendarCheck aria-hidden="true" /><strong>Réservations</strong><span>Voir les réservations de vos activités.</span></Link><Link href={"/partner/artworks" as Route}><BriefcaseBusiness aria-hidden="true"/><strong>Mes œuvres</strong><span>Consulter votre catalogue privé.</span></Link><Link href="/messages"><MessageCircle aria-hidden="true" /><strong>Messagerie</strong><span>Utiliser la messagerie Yeyamo existante.</span></Link></div><p className="yy-partner-note">Les revenus, commandes et statistiques ne sont pas affichés faute de source Partner fiable et isolée.</p></section>;
}

function ApplicationState({ profile, canEdit, canSubmit }: { profile: PartnerProfile; canEdit: boolean; canSubmit: boolean }) {
  const client = useQueryClient(); const submit = useMutation({ mutationFn: partnerPortalApi.submit, retry: false, onSuccess: () => void client.invalidateQueries({ queryKey: ["user", "partner"] }) });
  return <section className="yy-partner"><header><p className="yy-kicker">Candidature partenaire</p><h1>{profile.tradeName ?? profile.legalName}</h1><p>Statut backend : <strong>{profile.status}</strong></p>{profile.reviewComment ? <p role="status">Retour de vérification : {profile.reviewComment}</p> : null}</header>{canEdit ? <PartnerForm title="Mettre à jour la candidature" initial={editable(profile)} mode="update" /> : <p className="yy-partner-note">Votre dossier est en cours de traitement et ne peut pas être modifié.</p>}{canSubmit ? <div><Button type="button" disabled={submit.isPending} onClick={() => submit.mutate()}><Send aria-hidden="true" />{submit.isPending ? "Soumission…" : "Soumettre pour vérification"}</Button><p className="yy-partner-note">La soumission nécessite les documents KYC exigés par le Backend.</p>{submit.isError ? <p className="yy-form-error" role="alert">Soumission refusée. Vérifiez les champs et documents requis.</p> : null}</div> : null}</section>;
}

export function PartnerProfilePage() { const query = useQuery({ queryKey: ["user", "partner", "status"], queryFn: partnerPortalApi.status, retry: false }); if (query.isPending) return <Skeleton />; if (query.isError || !query.data?.profile) return <ErrorState title="Profil indisponible" message="Aucun profil partenaire actif n’est accessible." />; return <section className="yy-partner"><PartnerForm title="Profil professionnel" initial={editable(query.data.profile)} mode="update" disabled={!query.data.canEdit} /><Link href={"/partner" as Route}>Retour au dashboard</Link></section>; }

function PartnerForm({ title, initial, mode, disabled = false }: { title: string; initial: PartnerInput; mode: "create" | "update"; disabled?: boolean }) {
  const client = useQueryClient(); const [value, setValue] = useState(initial); const mutation = useMutation({ mutationFn: (body: PartnerInput) => mode === "create" ? partnerPortalApi.create(body) : partnerPortalApi.update(body), retry: false, onSuccess: () => void client.invalidateQueries({ queryKey: ["user", "partner"] }) });
  const text = (key: keyof PartnerInput, next: string) => setValue({ ...value, [key]: next.trim() ? next : null });
  const submit = (event: FormEvent) => { event.preventDefault(); mutation.mutate(value); };
  return <form className="yy-partner-form" onSubmit={submit}><h2>{title}</h2><fieldset disabled={disabled || mutation.isPending}><label>Raison sociale<input value={value.legalName} maxLength={160} required onChange={(e) => setValue({ ...value, legalName: e.target.value })} /></label><label>Nom commercial<input value={value.tradeName ?? ""} maxLength={160} onChange={(e) => text("tradeName", e.target.value)} /></label><label>Type d’activité<select value={value.businessType} onChange={(e) => setValue({ ...value, businessType: e.target.value as PartnerInput["businessType"] })}>{businessTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label>Email de contact<input type="email" required value={value.contactEmail} onChange={(e) => setValue({ ...value, contactEmail: e.target.value })} /></label><label>Numéro d’enregistrement<input value={value.registrationNumber ?? ""} maxLength={100} onChange={(e) => text("registrationNumber", e.target.value)} /></label><label>Pays principal (ISO-2)<input value={value.primaryCountryCode ?? ""} pattern="[A-Za-z]{2}" maxLength={2} onChange={(e) => text("primaryCountryCode", e.target.value.toUpperCase())} /></label><label className="yy-partner-wide">Description<textarea value={value.description ?? ""} maxLength={1000} onChange={(e) => text("description", e.target.value)} /></label>{!disabled ? <Button type="submit"><BriefcaseBusiness aria-hidden="true" />{mutation.isPending ? "Enregistrement…" : "Enregistrer"}</Button> : null}</fieldset>{mutation.isError ? <p className="yy-form-error" role="alert">L’enregistrement a été refusé par le Backend.</p> : null}</form>;
}
