import { z } from "zod";
import type { Passport } from "@/features/passport/types";
const uuid = z.string().uuid();
const instant = z.string().datetime({ offset: true });
const summary = z.object({ totalXp: z.number().int().nonnegative(), level: z.number().int().positive(), currentLevelThreshold: z.number().int().nonnegative(), nextLevelThreshold: z.number().int().positive(), currentLevelXp: z.number().int().nonnegative(), xpToNextLevel: z.number().int().nonnegative(), earnedBadgesCount: z.number().int().nonnegative(), passportStampsCount: z.number().int().nonnegative(), availableRewardsCount: z.number().int().nonnegative(), currentStreak: z.number().int().nonnegative(), longestStreak: z.number().int().nonnegative(), lastActivityDate: z.string().nullable(), updatedAt: instant });
const badge = z.object({ code: z.string(), name: z.string(), description: z.string(), earned: z.boolean(), earnedAt: instant.nullable() });
const stamp = z.object({ id: uuid, userId: z.string(), destinationId: z.string(), stampedAt: instant }).transform((value) => ({ id: value.id, destinationId: value.destinationId, stampedAt: value.stampedAt }));
const reward = z.object({ id: uuid, userId: z.string(), code: z.string(), title: z.string(), status: z.enum(["AVAILABLE", "CLAIMED", "EXPIRED"]), grantedAt: instant, claimedAt: instant.nullable(), source: z.string() }).transform((value) => ({ id: value.id, code: value.code, title: value.title, status: value.status, grantedAt: value.grantedAt, claimedAt: value.claimedAt, source: value.source }));
const objective = z.object({ id: uuid, label: z.string(), eventType: z.string(), metric: z.string(), target: z.number().int().positive(), current: z.number().int().nonnegative(), completed: z.boolean(), ruleKey: z.string().nullable(), ruleValue: z.string().nullable() }).transform((value) => ({ id: value.id, label: value.label, eventType: value.eventType, metric: value.metric, target: value.target, current: value.current, completed: value.completed }));
const mission = z.object({ id: uuid, code: z.string(), title: z.string(), description: z.string(), status: z.string(), startsAt: instant.nullable(), endsAt: instant.nullable(), rewardCode: z.string(), rewardTitle: z.string(), rewardAmount: z.number().int().positive(), objectives: z.array(objective), userStatus: z.string().nullable(), completedAt: instant.nullable() });
const missionReward = z.object({ id: uuid, missionCode: z.string(), code: z.string(), title: z.string(), amount: z.number().int().positive(), status: z.string(), grantedAt: instant.nullable(), failureReason: z.string().nullable() });
const history = z.object({ content: z.array(z.object({ id: uuid, points: z.number().int().positive(), reason: z.string(), sourceId: z.string(), occurredAt: instant })), number: z.number().int().nonnegative(), size: z.number().int().positive(), last: z.boolean() });
export function mapPassport(input: unknown): Passport { const value = z.object({ summary, badges: z.array(badge), stamps: z.array(stamp), rewards: z.array(reward), missions: z.array(mission), missionRewards: z.array(missionReward), history }).parse(input); return { ...value, history: { page: value.history.number, size: value.history.size, hasNext: !value.history.last, items: value.history.content } }; }
