export type PublicLocale = "fr" | "en";
export type ResourceSection = { id: string; title: string; paragraphs: string[]; steps?: string[] };
export type ResourceContent = { title: string; intro: string; sections: ResourceSection[] };

export const privacyContent: Record<PublicLocale, ResourceContent> = {
  fr: {
    title: "Politique de confidentialité",
    intro: "Comprendre les informations utilisées par YeYamo, les raisons de leur utilisation et les moyens de garder le contrôle sur votre vie privée.",
    sections: [
      { id: "scope", title: "1. À qui s’adresse cette politique ?", paragraphs: [
        "Cette politique concerne les visiteurs du site YeYamo, les utilisateurs de ses services de découverte, les contributeurs et les partenaires. Elle explique les traitements liés à la navigation, au compte, aux échanges avec l’équipe et aux fonctionnalités utilisées. Les données effectivement concernées dépendent de votre activité : la lecture d’une page publique ne nécessite pas les mêmes informations qu’une réservation ou une contribution.",
        "Dans cette politique, « données personnelles » désigne les informations qui permettent de vous identifier directement ou indirectement. Les sites, boutiques d’applications et services de partenaires accessibles par un lien disposent de leurs propres politiques, que nous vous invitons à consulter avant de leur transmettre des informations."
      ] },
      { id: "contact", title: "2. Nous contacter au sujet de vos données", paragraphs: [
        "Pour une question sur cette politique ou une demande relative à vos données, contactez l’équipe YeYamo à hello@yeyamo.cm en indiquant « Confidentialité » dans l’objet du message. Précisez le service concerné et, si nécessaire, l’adresse associée à votre compte afin de faciliter la recherche.",
        "Ne transmettez jamais votre mot de passe, un code de connexion, un numéro complet de carte bancaire ou une pièce d’identité sans demande justifiée. Lorsqu’une vérification est nécessaire pour protéger votre compte, seules les informations proportionnées à cette vérification doivent être demandées."
      ] },
      { id: "data", title: "3. Les catégories d’informations concernées", paragraphs: [
        "Informations de compte et de profil : identifiant, nom ou pseudonyme, coordonnées, image de profil, préférences et informations que vous choisissez de renseigner. Les champs obligatoires sont à distinguer des informations facultatives au moment de la collecte. Les éléments publiés sur votre profil peuvent être visibles selon les fonctionnalités et réglages proposés.",
        "Contenus et interactions : avis, commentaires, photos, récits, favoris, signalements et messages adressés au support, lorsque vous utilisez ces fonctionnalités. Avant de publier, vérifiez que vos contenus ne révèlent pas d’informations privées concernant une autre personne et que vous disposez des autorisations nécessaires.",
        "Données techniques : informations nécessaires à la communication avec le serveur, telles que l’adresse IP, le type de navigateur, les informations de session et les erreurs de fonctionnement. Pour les réservations, paiements ou démarches partenaires disponibles, des références de transaction, coordonnées et éléments nécessaires au traitement de la demande peuvent également être concernés."
      ] },
      { id: "purposes", title: "4. Pourquoi ces informations sont utilisées", paragraphs: [
        "Les informations nécessaires au service servent à permettre la connexion, fournir les fonctionnalités demandées, gérer vos préférences, répondre aux sollicitations et assurer le suivi des opérations. Les contributions servent à enrichir les contenus de découverte et les échanges au sein de la communauté.",
        "Les informations techniques et les signalements permettent de diagnostiquer les erreurs, prévenir les accès abusifs et traiter les contenus signalés. L’accès à une donnée doit correspondre à un besoin lié à ces finalités. Une nouvelle utilisation sensiblement différente doit faire l’objet d’une information appropriée et, lorsqu’il est requis, d’un accord préalable."
      ] },
      { id: "grounds", title: "5. Les fondements des traitements", paragraphs: [
        "Selon le traitement et la législation applicable, l’utilisation de vos données peut être nécessaire à la fourniture d’un service que vous demandez, au respect d’une obligation légale ou à un intérêt légitime tel que la protection du service contre la fraude. Un traitement fondé sur l’intérêt légitime doit tenir compte de vos droits et de vos attentes raisonnables.",
        "Lorsque le traitement repose sur votre consentement, vous devez pouvoir le retirer pour l’avenir. Le retrait ne remet pas en cause les traitements déjà réalisés sur ce fondement. Le refus d’une utilisation facultative ne doit pas vous empêcher de consulter les pages publiques qui ne nécessitent pas cette utilisation."
      ] },
      { id: "location", title: "6. Localisation et autorisations de l’appareil", paragraphs: [
        "Si une fonctionnalité vous propose des lieux à proximité, l’accès à la localisation dépend de l’autorisation accordée dans votre navigateur ou votre appareil. Vous pouvez refuser ou retirer cette autorisation dans les réglages de l’appareil. Une fonctionnalité reposant sur la proximité pourra alors être limitée.",
        "Les autorisations relatives aux photos, à la caméra ou aux notifications doivent correspondre à l’action que vous souhaitez effectuer. Examinez les autorisations affichées par votre appareil. Pensez également aux informations de localisation visibles dans les photos et les textes que vous publiez."
      ] },
      { id: "cookies", title: "7. Cookies et stockage de session", paragraphs: [
        "Le cookie de session « yeyamo_intro_seen » mémorise uniquement que l’introduction a été vue, afin de ne pas la rejouer pendant votre navigation. Il ne contient pas d’identifiant personnel, ne sert pas au suivi publicitaire et ne possède pas de date d’expiration persistante. Sa suppression dépend de la gestion des sessions de votre navigateur.",
        "L’espace d’administration utilise des cookies d’authentification pour maintenir une session et vérifier les accès. Le cookie d’accès expire selon la durée fournie lors de l’authentification. Les cookies de renouvellement et d’informations de session ont une durée maximale de 30 jours dans cette version du site. La déconnexion demande leur suppression du navigateur.",
        "La langue de la partie publique est indiquée dans l’adresse de la page avec le paramètre « lang ». Ce choix ne nécessite pas de cookie supplémentaire. Vous pouvez supprimer les cookies dans votre navigateur ; cette action peut fermer une session et imposer une nouvelle connexion.",
        "L’ajout de traceurs facultatifs, notamment publicitaires ou de mesure d’audience lorsque le consentement est requis, doit être accompagné d’informations sur leur finalité, leur fournisseur, leur durée et les moyens de les accepter ou de les refuser."
      ] },
      { id: "sharing", title: "8. Destinataires et contenus publics", paragraphs: [
        "Selon le service utilisé, les destinataires peuvent comprendre les membres autorisés de l’équipe, les prestataires nécessaires à l’hébergement et au fonctionnement du service, ainsi que les partenaires impliqués dans une opération que vous demandez. Une demande d’assistance peut être consultée par les personnes chargées de sa résolution.",
        "Une contribution publique peut être consultée, partagée ou copiée par d’autres personnes. Évitez d’y inclure des coordonnées privées, documents officiels ou informations sensibles. Une communication aux autorités peut être nécessaire lorsqu’une obligation légale ou une demande juridiquement valable l’impose."
      ] },
      { id: "retention", title: "9. Conservation et suppression", paragraphs: [
        "La conservation doit être limitée à ce qui est nécessaire pour la finalité concernée. Les données de compte sont liées à la durée de la relation avec le service ; une demande au support peut nécessiter un suivi jusqu’à sa résolution ; certains documents de transaction peuvent relever d’obligations légales de conservation.",
        "La fermeture d’un compte ne signifie pas nécessairement la suppression immédiate de toutes les informations : des éléments peuvent devoir être conservés pour une obligation légale, un litige ou la protection du service. Vous pouvez demander quelles durées ou quels critères s’appliquent à votre situation. Les éventuelles exceptions à une suppression doivent vous être expliquées."
      ] },
      { id: "security", title: "10. Sécurité et confidentialité des accès", paragraphs: [
        "L’espace d’administration utilise des contrôles de session et de permissions. Les cookies d’authentification sont inaccessibles au JavaScript de la page et configurés pour un transport sécurisé en production. Ces protections participent à la sécurité des accès sans constituer une garantie absolue contre tout incident.",
        "De votre côté, utilisez un mot de passe unique, gardez vos codes confidentiels et déconnectez-vous d’un appareil partagé. Si vous suspectez un accès non autorisé, contactez rapidement le support sans inclure de secret dans le message. Les incidents doivent être évalués et les notifications requises effectuées conformément aux règles applicables."
      ] },
      { id: "transfers", title: "11. Services externes et transferts", paragraphs: [
        "Les lieux de traitement peuvent dépendre des services techniques et partenaires utilisés. Lorsqu’un transfert international de données est concerné, les exigences de la législation applicable et les garanties nécessaires doivent être examinées. Vous pouvez contacter l’équipe pour obtenir des informations sur les destinataires et les garanties applicables à vos données.",
        "Ouvrir une boutique d’applications ou un site externe vous place dans l’environnement de ce tiers. Son traitement de vos données dépend de ses propres conditions et réglages. Cette politique ne remplace pas l’information fournie directement par ces services."
      ] },
      { id: "rights", title: "12. Vos droits et vos choix", paragraphs: [
        "Selon les règles applicables et le traitement concerné, vous pouvez demander l’accès à vos données, leur correction, leur suppression, la limitation d’un traitement ou la récupération de certaines données dans un format réutilisable. Vous pouvez également vous opposer à certains traitements et retirer un consentement pour l’avenir.",
        "Adressez votre demande à hello@yeyamo.cm en précisant le droit que vous souhaitez exercer et le service concerné. Une vérification proportionnée de votre identité peut être nécessaire. La réponse doit intervenir dans le délai prévu par la législation applicable ; une restriction ou un refus doit être expliqué. Vous pouvez vous adresser à l’autorité de protection des données compétente lorsque vous estimez que vos droits ne sont pas respectés."
      ] },
      { id: "children", title: "13. Protection des mineurs", paragraphs: [
        "Les mineurs doivent être accompagnés par un parent ou représentant légal lorsque la législation ou la fonctionnalité concernée l’exige. Ne publiez pas de coordonnées, de documents ni d’images permettant de mettre un enfant en danger. Signalez au support un contenu ou une collecte que vous estimez inapproprié afin qu’il soit examiné.",
        "Un parent ou représentant légal peut contacter l’équipe au sujet des données d’un enfant. Les éléments nécessaires à la vérification de la demande doivent rester limités à ce qui est utile pour protéger l’enfant et éviter une divulgation injustifiée."
      ] },
      { id: "updates", title: "14. Évolution de cette politique", paragraphs: [
        "Cette politique peut évoluer avec les fonctionnalités du service, les prestataires et les obligations applicables. La date de mise à jour permet d’identifier la version consultée. Un changement important concernant l’utilisation des données doit faire l’objet d’une information adaptée et, lorsque cela est nécessaire, d’un nouveau consentement.",
        "Les versions française et anglaise présentent les mêmes informations. Si un passage vous paraît ambigu, contactez l’équipe pour obtenir une explication avant de transmettre des informations sensibles."
      ] }
    ]
  },
  en: {
    title: "Privacy policy",
    intro: "Understand the information used by YeYamo, why it is used and how to stay in control of your privacy.",
    sections: [
      { id: "scope", title: "1. Who is this policy for?", paragraphs: [
        "This policy covers visitors to the YeYamo website, users of its discovery services, contributors and partners. It explains processing related to browsing, accounts, contact with the team and the features you use. The information involved depends on your activity: reading a public page does not require the same information as a booking or a contribution.",
        "In this policy, ‘personal data’ means information that identifies you directly or indirectly. Websites, app stores and partner services accessible through links have their own policies. Please read them before providing information to those services."
      ] },
      { id: "contact", title: "2. Contact us about your data", paragraphs: [
        "For questions about this policy or requests concerning your data, contact the YeYamo team at hello@yeyamo.cm with ‘Privacy’ in the subject line. Specify the service concerned and, where necessary, the email address associated with your account to help locate your information.",
        "Never send your password, a sign-in code, a complete payment card number or an identity document without a justified request. Where verification is needed to protect your account, only information proportionate to that verification should be requested."
      ] },
      { id: "data", title: "3. Categories of information", paragraphs: [
        "Account and profile information: identifier, name or username, contact details, profile image, preferences and information you choose to provide. Mandatory fields should be distinguished from optional information at collection. Profile details may be visible depending on the features and settings available.",
        "Content and interactions: reviews, comments, photographs, stories, saved places, reports and messages to support when you use these features. Before posting, check that your content does not disclose someone else’s private information and that you have the necessary permissions.",
        "Technical data: information needed to communicate with the server, such as IP address, browser type, session information and errors. For available booking, payment or partner processes, transaction references, contact details and information needed to handle the request may also be involved."
      ] },
      { id: "purposes", title: "4. Why information is used", paragraphs: [
        "Information needed to deliver the service enables sign-in, requested features, preference management, responses to enquiries and follow-up on operations. Contributions enrich discovery content and community exchanges.",
        "Technical information and reports help diagnose errors, prevent abusive access and review reported content. Access to information should meet a need related to these purposes. A materially different new use should be accompanied by appropriate information and prior agreement where required."
      ] },
      { id: "grounds", title: "5. Grounds for processing", paragraphs: [
        "Depending on the processing and applicable law, using your data may be necessary to provide a service you request, comply with a legal obligation or pursue a legitimate interest such as protecting the service against fraud. Processing based on legitimate interests must take your rights and reasonable expectations into account.",
        "Where processing relies on consent, you should be able to withdraw it for the future. Withdrawal does not affect processing already carried out on that basis. Refusing an optional use should not prevent you from reading public pages that do not require that use."
      ] },
      { id: "location", title: "6. Location and device permissions", paragraphs: [
        "If a feature suggests nearby places, access to location depends on permission in your browser or device. You can refuse or withdraw that permission in your device settings. Features that depend on proximity may then be limited.",
        "Photo, camera and notification permissions should correspond to the action you want to take. Review the permissions displayed by your device. Also consider location information visible in photographs and text you publish."
      ] },
      { id: "cookies", title: "7. Cookies and session storage", paragraphs: [
        "The session cookie ‘yeyamo_intro_seen’ records only that the introduction has been seen, so it does not replay while browsing. It contains no personal identifier, is not used for advertising tracking and has no persistent expiry date. Its removal depends on how your browser manages sessions.",
        "The administration area uses authentication cookies to maintain a session and verify access. The access cookie expires according to the lifetime provided during authentication. Refresh and session-information cookies have a maximum lifetime of 30 days in this version of the site. Signing out requests their removal from the browser.",
        "The public site’s language is included in the page address using the ‘lang’ parameter. This choice does not require an additional cookie. You can delete cookies in your browser; doing so may end a session and require you to sign in again.",
        "Adding optional trackers, including advertising or audience measurement where consent is required, should include information about their purpose, provider, lifetime and how to accept or reject them."
      ] },
      { id: "sharing", title: "8. Recipients and public content", paragraphs: [
        "Depending on the service used, recipients may include authorised team members, providers needed to host and operate the service, and partners involved in an operation you request. A support request may be viewed by the people responsible for resolving it.",
        "A public contribution can be viewed, shared or copied by other people. Avoid including private contact details, official documents or sensitive information. Disclosure to authorities may be necessary where a legal obligation or legally valid request requires it."
      ] },
      { id: "retention", title: "9. Retention and deletion", paragraphs: [
        "Retention should be limited to what is necessary for the relevant purpose. Account data is related to the duration of your relationship with the service; support enquiries may need follow-up until resolved; some transaction records may be subject to legal retention requirements.",
        "Closing an account does not necessarily mean all information is deleted immediately: some records may need to be retained for a legal obligation, a dispute or service protection. You can ask which periods or criteria apply to your situation. Any exceptions to deletion should be explained to you."
      ] },
      { id: "security", title: "10. Security and access confidentiality", paragraphs: [
        "The administration area uses session and permission controls. Authentication cookies are inaccessible to page JavaScript and configured for secure transport in production. These protections contribute to access security without providing an absolute guarantee against every incident.",
        "Use a unique password, keep your codes confidential and sign out on shared devices. If you suspect unauthorised access, contact support promptly without including secrets in your message. Incidents should be assessed and required notifications made in accordance with applicable rules."
      ] },
      { id: "transfers", title: "11. External services and transfers", paragraphs: [
        "Processing locations may depend on the technical services and partners used. Where international data transfers are involved, applicable legal requirements and necessary safeguards must be considered. You can contact the team for information about recipients and safeguards relevant to your data.",
        "Opening an app store or external website takes you into that third party’s environment. Its handling of your information depends on its own terms and settings. This policy does not replace information supplied directly by those services."
      ] },
      { id: "rights", title: "12. Your rights and choices", paragraphs: [
        "Depending on applicable rules and the processing concerned, you may request access to your data, correction, deletion, restriction of processing or receipt of certain data in a reusable format. You may also object to certain processing and withdraw consent for the future.",
        "Send your request to hello@yeyamo.cm, specifying the right you wish to exercise and the service concerned. Proportionate identity verification may be necessary. A response should be provided within the legally applicable period, and any restriction or refusal should be explained. You can contact the competent data protection authority if you believe your rights have not been respected."
      ] },
      { id: "children", title: "13. Protecting minors", paragraphs: [
        "Minors should be accompanied by a parent or legal representative when required by law or by the relevant feature. Do not publish contact details, documents or images that could endanger a child. Report content or collection you consider inappropriate to support so it can be reviewed.",
        "A parent or legal representative can contact the team about a child’s data. Information needed to verify the request should be limited to what is useful to protect the child and prevent unjustified disclosure."
      ] },
      { id: "updates", title: "14. Changes to this policy", paragraphs: [
        "This policy may evolve with service features, providers and applicable obligations. The update date identifies the version you are reading. Significant changes to data use should be communicated appropriately and new consent obtained where necessary.",
        "The French and English versions present the same information. If a passage seems unclear, contact the team for an explanation before providing sensitive information."
      ] }
    ]
  }
};

export const documentationContent: Record<PublicLocale, ResourceContent> = {
  fr: {
    title: "Le guide YeYamo",
    intro: "Préparez vos découvertes, partagez vos expériences et trouvez de l’aide. Des repères pratiques pour chaque étape de votre parcours.",
    sections: [
      { id: "getting-started", title: "Bien démarrer", paragraphs: ["YeYamo met en relation les voyageurs, les créateurs et les acteurs locaux autour des lieux, de la culture et des expériences en Afrique. Les pages Fonctionnalités et Destinations présentent les usages et les lieux ; les interactions telles que les favoris ou les contributions dépendent des fonctionnalités disponibles dans votre application.", "Commencez par une destination et un objectif : découvrir un site culturel, préparer une sortie nature ou trouver une expérience locale. Vous pourrez ensuite comparer les informations utiles avant de choisir."], steps: ["Ouvrez les pages Destinations et Fonctionnalités depuis le menu principal.", "Consultez la rubrique Téléchargement pour connaître les accès mobiles proposés. Si une boutique n’est pas encore disponible, contactez l’équipe.", "Lorsqu’un compte est nécessaire dans l’application, utilisez vos propres coordonnées et un mot de passe unique.", "Lisez les informations de confidentialité et choisissez les autorisations adaptées à votre usage."] },
      { id: "explore", title: "Explorer et préparer une visite", paragraphs: ["Utilisez la recherche, la carte ou les filtres lorsqu’ils sont proposés pour cibler une zone et une catégorie. Comparez les descriptions et les informations pratiques des lieux. Une note ou une photographie donne un aperçu ; elle ne remplace pas la vérification des conditions de visite.", "Avant de partir, confirmez les horaires, l’accessibilité, les tarifs et les conditions d’accès auprès du lieu ou de l’organisateur. Pour une sortie nature, prévoyez le trajet, les conditions météo et l’accompagnement nécessaire."], steps: ["Choisissez une région ou une ville, puis une catégorie adaptée à votre sortie.", "Consultez la fiche du lieu et repérez sa localisation et ses informations pratiques.", "Vérifiez les informations susceptibles de changer auprès du contact indiqué.", "Préparez votre trajet et conservez les informations utiles avant le départ."] },
      { id: "saved-places", title: "Retrouver ses favoris", paragraphs: ["Lorsqu’une fonction de favoris est disponible, elle permet de conserver une sélection de lieux pour préparer une sortie. Enregistrez les fiches qui vous intéressent et retrouvez-les depuis la rubrique correspondante de votre compte.", "Si un favori semble absent, vérifiez que vous utilisez le même compte et que la connexion a permis la synchronisation. Un lieu supprimé ou rendu indisponible peut ne plus être consultable. Ne supposez pas que toutes les fiches sont accessibles hors connexion : vérifiez leur disponibilité avant de voyager."] },
      { id: "contribute", title: "Partager une expérience utile", paragraphs: ["Un avis utile décrit une expérience personnelle et donne des détails concrets : contexte de visite, accessibilité, accueil ou conseil pratique. Distinguez vos impressions des faits et évitez les accusations non vérifiables.", "Publiez uniquement des textes et médias que vous avez le droit de partager. Demandez l’accord des personnes reconnaissables et ne divulguez pas de coordonnées privées. Les contributions peuvent être examinées dans le cadre de la modération."], steps: ["Ouvrez le lieu ou l’expérience concernée dans l’application.", "Utilisez l’action de contribution si elle est disponible pour votre compte.", "Rédigez un retour précis et ajoutez des médias pertinents.", "Relisez votre publication pour supprimer les données personnelles et corriger les erreurs."] },
      { id: "bookings", title: "Réservations et paiements", paragraphs: ["Si une expérience propose une réservation, vérifiez la date, le nombre de participants, le prix total, le prestataire et les conditions d’annulation avant de confirmer. La disponibilité d’une réservation dépend de l’offre et du partenaire.", "En cas de paiement en attente, consultez le statut de l’opération avant de recommencer. Conservez la référence de réservation ou de transaction pour le support. Ne communiquez jamais de code de validation ni de numéro complet de carte. Les possibilités d’annulation ou de remboursement dépendent des conditions présentées pour l’offre."] },
      { id: "partners", title: "Pour les partenaires locaux", paragraphs: ["Pour présenter un lieu, une activité ou une offre, contactez l’équipe en décrivant votre structure, votre zone d’activité et le service proposé. Utilisez une adresse de contact professionnelle lorsque vous en disposez.", "Préparez une description exacte, des coordonnées à jour et des images dont vous détenez les droits. L’équipe pourra préciser les modalités de vérification et d’accès adaptées à votre profil. Les documents justificatifs doivent être transmis uniquement par le canal indiqué pour votre dossier."] },
      { id: "account", title: "Compte et confidentialité", paragraphs: ["Gardez vos identifiants confidentiels et déconnectez-vous des appareils partagés. Les permissions de localisation et de notifications peuvent être modifiées dans les réglages de votre appareil. Leur désactivation peut limiter certaines fonctionnalités.", "Pour demander une correction, l’accès à vos données ou la suppression d’un compte, écrivez à hello@yeyamo.cm en précisant votre demande. La politique de confidentialité explique les droits, les vérifications éventuelles et les limites applicables à la suppression."] },
      { id: "troubleshooting", title: "Résoudre les difficultés courantes", paragraphs: ["Connexion impossible : vérifiez votre connexion réseau et l’adresse du compte. Si un parcours de récupération est proposé, utilisez-le. Sinon, contactez le support sans transmettre votre mot de passe.", "Carte ou proximité indisponible : vérifiez les autorisations de localisation et la connexion. Essayez une recherche par ville lorsque cette option est proposée.", "Contenu non visible ou en attente : vérifiez le compte utilisé et l’état de publication. Un contenu peut être soumis à validation ou retiré à la suite d’un signalement.", "Page ou application bloquée : actualisez la page ou relancez l’application. Si le problème persiste, notez l’heure, la page concernée et le message affiché pour aider le support."] },
      { id: "integrations", title: "Intégrations et accès techniques", paragraphs: ["Pour une intégration avec YeYamo, contactez hello@yeyamo.cm en indiquant votre organisation, le cas d’usage, les données nécessaires et le volume envisagé. L’équipe doit confirmer les accès disponibles et fournir les spécifications correspondant à votre projet.", "Cette documentation publique ne fournit pas de clés ni de contrat d’API public. N’utilisez pas les accès d’administration pour connecter un service tiers. Une intégration doit disposer d’autorisations adaptées et de consignes de sécurité propres à son usage."] },
      { id: "support", title: "Contacter le support", paragraphs: ["Écrivez à hello@yeyamo.cm avec un objet précis, le service concerné, les étapes qui ont conduit au problème et le résultat attendu. Ajoutez une référence de réservation ou un message d’erreur si cela aide à comprendre la situation.", "Vous pouvez aussi joindre l’équipe aux numéros +237 658 940 985 et +237 676 219 440. Avant de partager une capture d’écran, masquez les informations personnelles et les secrets de connexion. Pour les questions relatives aux données personnelles, indiquez « Confidentialité » dans l’objet de votre message."] }
    ]
  },
  en: {
    title: "The YeYamo guide",
    intro: "Plan your discoveries, share your experiences and find help. Practical guidance for every step of your journey.",
    sections: [
      { id: "getting-started", title: "Getting started", paragraphs: ["YeYamo connects travellers, creators and local businesses around places, culture and experiences across Africa. The Features and Destinations pages introduce use cases and places; interactions such as saved places or contributions depend on the features available in your app.", "Start with a destination and a goal: discover a cultural site, plan a nature outing or find a local experience. Then compare useful information before choosing."], steps: ["Open the Destinations and Features pages from the main menu.", "Check the Download section for the mobile access offered. If a store is not yet available, contact the team.", "When an account is required in the app, use your own contact details and a unique password.", "Read the privacy information and choose permissions that suit your use."] },
      { id: "explore", title: "Explore and plan a visit", paragraphs: ["Use search, maps or filters where available to focus on an area and category. Compare place descriptions and practical details. A rating or photograph provides an impression; it does not replace checking visiting conditions.", "Before leaving, confirm opening hours, accessibility, prices and entry requirements with the venue or organiser. For a nature trip, plan your route, check weather conditions and arrange any necessary guidance."], steps: ["Choose a region or city and a category that suits your outing.", "Read the place listing and identify its location and practical details.", "Confirm information that may change with the listed contact.", "Plan your route and keep useful information before leaving."] },
      { id: "saved-places", title: "Find your saved places", paragraphs: ["Where a favourites feature is available, it lets you keep a selection of places to plan an outing. Save listings you find interesting and return to them in the relevant account section.", "If a saved place appears to be missing, check that you are using the same account and that your connection has allowed synchronisation. A deleted or unavailable place may no longer be accessible. Do not assume every listing is available offline: check before travelling."] },
      { id: "contribute", title: "Share a useful experience", paragraphs: ["A useful review describes a personal experience and provides concrete details: visit context, accessibility, hospitality or practical advice. Distinguish impressions from facts and avoid unverifiable accusations.", "Only post text and media you have the right to share. Ask permission from recognisable people and do not disclose private contact details. Contributions may be reviewed through moderation."], steps: ["Open the relevant place or experience in the app.", "Use the contribution action if it is available for your account.", "Write specific feedback and add relevant media.", "Review your post to remove personal information and correct errors."] },
      { id: "bookings", title: "Bookings and payments", paragraphs: ["If an experience offers booking, check the date, number of participants, total price, provider and cancellation terms before confirming. Booking availability depends on the offer and partner.", "If a payment is pending, check its status before trying again. Keep the booking or transaction reference for support. Never share a verification code or complete card number. Cancellation and refund options depend on the terms shown for the offer."] },
      { id: "partners", title: "For local partners", paragraphs: ["To present a place, activity or offer, contact the team describing your organisation, operating area and proposed service. Use a business contact address where you have one.", "Prepare an accurate description, current contact details and images you have the rights to use. The team can explain verification and access arrangements for your profile. Supporting documents should only be sent through the channel specified for your application."] },
      { id: "account", title: "Account and privacy", paragraphs: ["Keep your credentials confidential and sign out on shared devices. Location and notification permissions can be changed in your device settings. Disabling them may limit certain features.", "To request a correction, access to your data or account deletion, write to hello@yeyamo.cm and explain your request. The privacy policy describes rights, possible verification and applicable limits on deletion."] },
      { id: "troubleshooting", title: "Solve common problems", paragraphs: ["Cannot sign in: check your network connection and account address. If an account recovery flow is offered, use it. Otherwise, contact support without sending your password.", "Map or nearby places unavailable: check location permissions and your connection. Try searching by city when that option is offered.", "Content missing or pending: check the account you are using and publication status. Content may require approval or be removed following a report.", "Page or app stuck: refresh the page or restart the app. If the problem continues, note the time, affected page and displayed message to help support."] },
      { id: "integrations", title: "Integrations and technical access", paragraphs: ["For a YeYamo integration, contact hello@yeyamo.cm with your organisation, use case, required data and expected volume. The team must confirm available access and provide specifications for your project.", "This public documentation does not provide keys or a public API contract. Do not use administration credentials to connect a third-party service. An integration needs appropriate permissions and security instructions for its use."] },
      { id: "support", title: "Contact support", paragraphs: ["Write to hello@yeyamo.cm with a clear subject, the relevant service, steps leading to the problem and the expected result. Include a booking reference or error message if it helps explain the situation.", "You can also reach the team on +237 658 940 985 and +237 676 219 440. Before sharing a screenshot, hide personal information and sign-in secrets. For personal-data enquiries, include ‘Privacy’ in your message subject."] }
    ]
  }
};
