import { apiFetch, jsonRequest } from "@/lib/api/client";
import type { Reservation, ReservationDetail, ReservationFilters, ReservationHistory, ReservationPage } from "@/features/reservations/types/reservation";
const query = (filters: ReservationFilters) => { const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => value !== undefined && value !== "" && params.set(key, String(value))); return params.toString(); };
export const reservationsApi = {
  list: (filters: ReservationFilters) => apiFetch<Omit<ReservationPage,"content">&{content:Array<Omit<Reservation,"activityId"|"totalAmount"|"status">>}>(`/api/v1/booking-management/bookings?${query(filters)}`).then(page=>({...page,content:page.content.map(item=>({...item,activityId:item.resourceId,totalAmount:item.amount,status:item.bookingStatus}))})),
  detail: (id: string) => apiFetch<{booking:Omit<Reservation,"activityId"|"totalAmount"|"status">;statusHistory:ReservationHistory[];user?:ReservationDetail["user"];partner?:ReservationDetail["partner"];resource?:ReservationDetail["resource"];payment?:ReservationDetail["payment"];supportNotes:string[];confirmedAt?:string|null;cancelledAt?:string|null;completedAt?:string|null}>(`/api/v1/booking-management/bookings/${id}`).then(detail=>({...detail.booking,activityId:detail.booking.resourceId,totalAmount:detail.booking.amount,status:detail.booking.bookingStatus,slotId:detail.resource?.slotId,quantity:null,unitPrice:detail.booking.amount,cancellationReason:null,statusHistory:detail.statusHistory,user:detail.user,partner:detail.partner,resource:detail.resource,payment:detail.payment,supportNotes:detail.supportNotes,confirmedAt:detail.confirmedAt,cancelledAt:detail.cancelledAt,completedAt:detail.completedAt})),
  history: (id: string) => apiFetch<ReservationHistory[]>(`/api/v1/bookings/${id}/history`),
  cancel: (id: string, reason: string) => apiFetch<Reservation>(`/api/v1/booking-management/bookings/${id}/cancel`, jsonRequest("POST", { reason }, { "Idempotency-Key": crypto.randomUUID() })),
  complete: (id: string) => apiFetch<Reservation>(`/api/v1/booking-management/bookings/${id}/complete`, jsonRequest("POST", undefined, { "Idempotency-Key": crypto.randomUUID() }))
};
