"use client";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { geographyApi } from "@/features/geography/api/geography-api";
import { AdminDataTable, type AdminColumn } from "@/components/admin/ui/admin-data-table";
import { AdminEmptyState, AdminPageHeader } from "@/components/admin/ui/admin-foundation";
import type { City, District, PlaceCategory, Region } from "@/features/geography/types/geography";
type Reference = Region | City | District | PlaceCategory;
export function ReferencePage({kind}:{kind:"regions"|"cities"|"districts"|"categories"}){const[parent,setParent]=useState("");const query=useQuery<Reference[]>({queryKey:["geography",kind,parent],queryFn:async()=>{if(kind==="regions")return geographyApi.regions();if(kind==="cities")return geographyApi.cities(Number(parent));if(kind==="districts")return geographyApi.districts(Number(parent));return geographyApi.categories()},enabled:kind==="regions"||kind==="categories"||Boolean(parent)});const columns:AdminColumn<Reference>[]=[{id:"id",header:"ID",cell:(r)=>r.id},{id:"name",header:"Nom",cell:(r)=>r.name},{id:"slug",header:"Slug",cell:(r)=>"slug"in r?r.slug:"—"},{id:"coordinates",header:"Coordonnées",cell:(r)=>"latitude"in r?`${r.latitude??"—"}, ${r.longitude??"—"}`:"—"}];const title={regions:"Régions",cities:"Villes",districts:"Districts / quartiers",categories:"Catégories de lieux"}[kind];return <div className="admin-feature"><AdminPageHeader title={title} description={kind==="categories"?"Lecture seule : place-service n’expose aucun endpoint d’écriture pour les catégories.":"Création et modification disponibles dans le backend ; suppression non exposée."}/>{kind==="cities"||kind==="districts"?<section className="admin-filters"><input type="number" placeholder={kind==="cities"?"ID région":"ID ville"} value={parent} onChange={(e)=>setParent(e.target.value)}/></section>:null}<section className="admin-section-card">{!query.isLoading&&!query.data&&parent===""?<AdminEmptyState title="Sélection requise"/>:<AdminDataTable rows={query.data??[]} columns={columns} rowKey={(r)=>String(r.id)} loading={query.isLoading} error={query.error??undefined}/>}</section></div>}
