"use client";
import Link from "next/link"; import type { Route } from "next"; import { useEffect, useState } from "react"; import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { platformUsersApi } from "@/features/users/api/platform-users-api"; import type { PlatformUser } from "@/features/users/types/platform-user"; import { queryKeys } from "@/lib/query/query-keys"; import { useAdminUrlState } from "@/lib/url-state"; import { AdminDataTable, type AdminColumn } from "@/components/admin/ui/admin-data-table"; import { AdminConfirmDialog, AdminDateRangePicker, AdminFilters, AdminPageHeader, AdminSearchInput, AdminSort, AdminStatusBadge } from "@/components/admin/ui/admin-foundation"; import { Can } from "@/features/auth/permissions"; import { useAdminToast } from "@/components/admin/ui/admin-toast";

export function PlatformUsersPage() { const { state, update, reset } = useAdminUrlState(); const [search, setSearch] = useState(state.search); const [action, setAction] = useState<{ user: PlatformUser; status: "SUSPENDED" | "ACTIVE" }>(); const client = useQueryClient(); const { toast } = useAdminToast(); useEffect(() => { const timer = window.setTimeout(() => update({ search, page: 0 }), 350); return () => window.clearTimeout(timer); }, [search]);
  const filters = { page: state.page, size: state.size, search: state.search || undefined, status: state.status, sort: state.sort, createdFrom: state.from, createdTo: state.to }; const query = useQuery({ queryKey: queryKeys.users.list(filters), queryFn: () => platformUsersApi.list(filters) }); const mutation = useMutation({ mutationFn: ({ user, status }: NonNullable<typeof action>) => platformUsersApi.status(user.id, { status, reason: status === "SUSPENDED" ? "Suspension administrative" : "Réactivation administrative" }), onSuccess: async () => { toast({ title: "Statut utilisateur mis à jour", tone: "success" }); setAction(undefined); await client.invalidateQueries({ queryKey: queryKeys.users.all }); } });
  const columns: AdminColumn<PlatformUser>[] = [
    { id:"avatar",header:"Avatar",cell:(u)=><span className="admin-avatar">{u.avatarUrl ? <img src={u.avatarUrl} alt="" /> : (u.displayName ?? u.email ?? "U")[0]}</span> }, {id:"name",header:"Nom",cell:(u)=>u.displayName ?? "Non exposé"}, {id:"username",header:"Username",cell:(u)=>u.username ?? "Non exposé"}, {id:"email",header:"Email",cell:(u)=>u.email ?? "—"}, {id:"phone",header:"Téléphone",cell:(u)=>u.phone ?? "—"}, {id:"roles",header:"Rôle/type",cell:(u)=>u.roles.join(", ") || "—"}, {id:"region",header:"Région",cell:(u)=>u.region ?? "Non exposée"}, {id:"status",header:"Statut",cell:(u)=><AdminStatusBadge status={u.status}/>}, {id:"createdAt",header:"Création",sortable:true,cell:(u)=>new Date(u.createdAt).toLocaleDateString("fr-FR")}, {id:"lastLoginAt",header:"Dernière connexion",sortable:true,cell:(u)=>u.lastLoginAt ? new Date(u.lastLoginAt).toLocaleString("fr-FR") : "Non exposée"}
  ];
  return <div className="admin-feature"><AdminPageHeader title="Utilisateurs plateforme" description="Population YeYamo — distincte des comptes administrateurs." actions={<Can roles={["ADMIN","SUPER_ADMIN"]}><a className="admin-button" href={platformUsersApi.exportUrl}>Exporter</a></Can>} /><AdminFilters onReset={reset}><AdminSearchInput value={search} onChange={setSearch}/><select value={state.status ?? ""} onChange={(e)=>update({status:e.target.value,page:0})}><option value="">Tous les statuts</option><option>ACTIVE</option><option>SUSPENDED</option><option>DISABLED</option><option>BANNED</option></select><input placeholder="Rôle" value={new URLSearchParams(typeof window === "undefined" ? "" : window.location.search).get("role") ?? ""} onChange={(e)=>update({role:e.target.value,page:0} as never)}/><input placeholder="Région" onChange={(e)=>update({region:e.target.value,page:0} as never)}/><AdminDateRangePicker from={state.from} to={state.to} onChange={(range)=>update({...range,page:0})}/><AdminSort value={state.sort} options={[{value:"createdAt,desc",label:"Plus récents"},{value:"lastLoginAt,desc",label:"Dernières connexions"}]} onChange={(sort)=>update({sort,page:0})}/></AdminFilters><section className="admin-section-card"><AdminDataTable rows={query.data?.content ?? []} columns={columns} rowKey={(u)=>u.id} loading={query.isLoading} error={query.error ?? undefined} page={state.page} size={state.size} total={query.data?.totalElements} onPageChange={(page)=>update({page})} onSizeChange={(size)=>update({size,page:0})} onSort={(sort)=>update({sort,page:0})} actions={(user)=><div className="admin-row-actions"><Link href={`/admin/users/${user.id}` as Route}>Consulter</Link><Can roles={["ADMIN","SUPER_ADMIN"]}><button onClick={()=>setAction({user,status:user.status === "SUSPENDED" ? "ACTIVE" : "SUSPENDED"})}>{user.status === "SUSPENDED" ? "Réactiver" : "Suspendre"}</button></Can></div>}/></section><AdminConfirmDialog open={Boolean(action)} title={action?.status === "SUSPENDED" ? "Suspendre l’utilisateur" : "Réactiver l’utilisateur"} message="Cette action sera tracée et doit être confirmée." destructive={action?.status === "SUSPENDED"} busy={mutation.isPending} onClose={()=>setAction(undefined)} onConfirm={()=>action && mutation.mutate(action)}/></div>;
}
