"use client";

import { useQuery } from "@tanstack/react-query";
import { ExternalLink, Heart, MapPin, Share2 } from "lucide-react";
import { Button, ErrorState, Skeleton } from "@/components/public/ui";
import { explorerApi } from "@/features/explorer/api";
import { useProtectedAction } from "@/features/user-auth/protected-action-context";

function Share({ title }: { title: string }) { return <Button type="button" className="yy-detail-action" onClick={() => { const url = window.location.href; if (navigator.share) void navigator.share({ title, url }); else void navigator.clipboard?.writeText(url); }}><Share2 aria-hidden="true" />Partager</Button>; }
export function PlaceDetailPage({ id }: { id: string }) { const protectedAction = useProtectedAction(); const query = useQuery({ queryKey: ["public", "place", id], queryFn: () => explorerApi.place(id), retry: false }); if (query.isLoading) return <div className="yy-detail yy-detail-skeleton"><Skeleton /><Skeleton /></div>; if (query.isError || !query.data) return <ErrorState title="Lieu indisponible" message="Ce lieu public est introuvable ou ne peut pas être affiché." />; const place = query.data; const directions = place.latitude !== null && place.longitude !== null ? `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${place.latitude},${place.longitude}`)}` : place.address ? `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(place.address)}` : null; return <article className="yy-detail"><header><p className="yy-kicker">Lieu</p><h1>{place.name}</h1>{place.categoryName ? <p>{place.categoryName}</p> : null}</header>{place.media.length ? <div className="yy-detail-media">{place.media.map((media) => <img key={media.id} src={media.url} alt="" />)}</div> : null}<div className="yy-detail-layout"><div>{place.description ? <section><h2>À propos</h2><p>{place.description}</p></section> : null}{place.schedules.length ? <section><h2>Horaires</h2><ul>{place.schedules.map((schedule) => <li key={schedule.id}>{schedule.openTime} – {schedule.closeTime}</li>)}</ul></section> : null}</div><aside><p>{place.address ?? "Adresse non renseignée"}</p><div className="yy-detail-actions"><Share title={place.name} />{directions ? <a className="yy-button yy-detail-action" href={directions} target="_blank" rel="noreferrer"><MapPin aria-hidden="true" />Itinéraire</a> : null}{place.website?.startsWith("https://") || place.website?.startsWith("http://") ? <a className="yy-button yy-detail-action" href={place.website} target="_blank" rel="noreferrer"><ExternalLink aria-hidden="true" />Site web</a> : null}<Button type="button" className="yy-detail-action" onClick={() => protectedAction({ reason: "Connectez-vous pour enregistrer un lieu", level: "L1", intent: { type: "FAVORITE", resourceType: "place", resourceId: id }, run: () => undefined })}><Heart aria-hidden="true" />Favori</Button></div></aside></div></article>; }
export function EventDetailPage({ id }: { id: string }) { const protectedAction = useProtectedAction(); const query = useQuery({ queryKey: ["public", "event", id], queryFn: () => explorerApi.event(id), retry: false }); if (query.isLoading) return <div className="yy-detail yy-detail-skeleton"><Skeleton /><Skeleton /></div>; if (query.isError || !query.data) return <ErrorState title="Événement indisponible" message="Cet événement public est introuvable ou ne peut pas être affiché." />; const event = query.data; return <article className="yy-detail"><header><p className="yy-kicker">Événement</p><h1>{event.title}</h1><p>{new Intl.DateTimeFormat("fr-FR", { dateStyle: "full", timeStyle: "short" }).format(new Date(event.startAt))}</p></header><div className="yy-detail-layout"><div>{event.description ? <section><h2>À propos</h2><p>{event.description}</p></section> : null}</div><aside><p>Statut : {event.status}</p><p>{event.registeredCount}{event.capacity !== null ? ` / ${event.capacity}` : ""} participant{event.registeredCount > 1 ? "s" : ""}</p><div className="yy-detail-actions"><Share title={event.title} /><Button type="button" className="yy-detail-action" onClick={() => protectedAction({ reason: "Connectez-vous pour participer à cet événement", level: "L2", run: () => undefined })}>Participer</Button></div></aside></div></article>; }
