"use client";
import Link from "next/link";
import type { Route } from "next";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bell, CheckCheck, FolderHeart, Plus } from "lucide-react";
import { Button, EmptyState, ErrorState, Skeleton } from "@/components/public/ui";
import { userAuthFetch } from "@/lib/user-auth/client";
import { notificationHref } from "@/features/engagement/mapper";
import type { CollectionSummary, Notification, Page } from "@/features/engagement/types";
async function collections() { return userAuthFetch<Page<CollectionSummary>>("/api/user/collections?page=0&size=20"); }
async function notifications() { return userAuthFetch<Page<Notification>>("/api/user/notifications?page=0&size=20"); }
export function CollectionsPage() { const client = useQueryClient(); const query = useQuery({ queryKey: ["user", "collections", 0], queryFn: collections }); const create = useMutation({ mutationFn: () => userAuthFetch("/api/user/collections", { method: "POST", body: JSON.stringify({ title: "Nouvelle collection", description: null, isPublic: false, coverAssetId: null }), headers: { "Idempotency-Key": crypto.randomUUID() } }), onSuccess: () => void client.invalidateQueries({ queryKey: ["user", "collections"] }) }); if (query.isPending) return <Skeleton />; if (query.isError) return <ErrorState title="Collections indisponibles" message="Vos collections ne peuvent pas être chargées." />; return <section className="yy-engagement"><header><div><p className="yy-kicker">Privé</p><h1>Mes collections</h1></div><Button type="button" disabled={create.isPending} onClick={() => create.mutate()}><Plus aria-hidden="true" />Créer</Button></header>{query.data.items.length ? <div className="yy-engagement-grid">{query.data.items.map((item) => <article key={item.id}><FolderHeart aria-hidden="true" /><h2>{item.title}</h2>{item.description ? <p>{item.description}</p> : null}<small>{item.placeCount} lieu{item.placeCount > 1 ? "x" : ""} · {item.isPublic ? "Publique" : "Privée"}</small></article>)}</div> : <EmptyState title="Aucune collection" message="Créez une collection pour organiser vos lieux enregistrés." />}</section>; }
export function NotificationsPage() { const client = useQueryClient(); const query = useQuery({ queryKey: ["user", "notifications", 0], queryFn: notifications, refetchInterval: 60_000 }); const markAll = useMutation({ mutationFn: () => userAuthFetch("/api/user/notifications/read-all", { method: "POST" }), onSuccess: () => { void client.invalidateQueries({ queryKey: ["user", "notifications"] }); void client.invalidateQueries({ queryKey: ["user", "notification-count"] }); } }); const markOne = useMutation({ mutationFn: (id: string) => userAuthFetch(`/api/user/notifications/${id}/read`, { method: "POST" }), onSuccess: () => { void client.invalidateQueries({ queryKey: ["user", "notifications"] }); void client.invalidateQueries({ queryKey: ["user", "notification-count"] }); } }); if (query.isPending) return <Skeleton />; if (query.isError) return <ErrorState title="Notifications indisponibles" message="Vos notifications ne peuvent pas être chargées." />; return <section className="yy-engagement"><header><div><p className="yy-kicker">Privé</p><h1>Notifications</h1></div><Button type="button" disabled={markAll.isPending} onClick={() => markAll.mutate()}><CheckCheck aria-hidden="true" />Tout lire</Button></header>{query.data.items.length ? <ol className="yy-notification-list">{query.data.items.map((item) => <li key={item.id} data-unread={item.readAt === null}><Bell aria-hidden="true" /><div><strong>{item.title}</strong><p>{item.body}</p><time dateTime={item.createdAt}>{new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium" }).format(new Date(item.createdAt))}</time>{notificationHref(item) ? <Link href={notificationHref(item)! as Route}>Ouvrir</Link> : null}</div>{item.readAt === null ? <button type="button" onClick={() => markOne.mutate(item.id)}>Marquer comme lue</button> : <span>Lu</span>}</li>)}</ol> : <EmptyState title="Aucune notification" message="Vos nouvelles activités apparaîtront ici." />}</section>; }
