"use client";
import Link from "next/link";
import { CalendarDays, ChevronDown, LogOut, Menu, Search, ShieldCheck, UserCircle2 } from "lucide-react";
import { usePathname, useRouter } from "next/navigation";
import { useState } from "react";
import { getModuleByHref } from "@/lib/admin-config";
import { useAdminSession } from "@/features/auth/session-context";
import { AdminNotificationBell } from "@/features/notifications/components/admin-notifications";

function copy(pathname:string){if(pathname==="/admin")return{title:"Tableau de bord",subtitle:"Bienvenue sur l’administration YeYamo"};const adminModule=getModuleByHref(pathname);return adminModule?{title:adminModule.label,subtitle:adminModule.summary}:{title:"Administration YeYamo",subtitle:"Pilotage des espaces, contenus et performances"}}
export function Topbar({onMenuClick}:{onMenuClick:()=>void}){const pathname=usePathname();const router=useRouter();const{session}=useAdminSession();const[open,setOpen]=useState(false);const current=copy(pathname);const name=[session?.firstName,session?.lastName].filter(Boolean).join(" ")||session?.email||"Administrateur";async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.replace("/admin/login");router.refresh()}return <header className="admin-topbar"><div className="admin-topbar__headline"><button type="button" className="admin-topbar__menu" onClick={onMenuClick} aria-label="Ouvrir le menu"><Menu size={20}/></button><div><h1 className="admin-topbar__title">{current.title}</h1><p className="admin-topbar__subtitle">{current.subtitle}</p></div></div><div className="admin-topbar__actions"><label className="admin-topbar__search"><Search size={18}/><input type="search" placeholder="Rechercher…" aria-label="Recherche globale"/></label><AdminNotificationBell/><button type="button" className="admin-topbar__period"><CalendarDays size={18}/><span>Période</span></button><div className="admin-topbar__account"><button type="button" className="admin-topbar__user" aria-expanded={open} onClick={()=>setOpen(value=>!value)}><span className="admin-topbar__user-avatar"><UserCircle2 size={18}/></span><span className="admin-topbar__identity"><strong>{name}</strong><small>{session?.roles[0]??"Session"}</small></span><ChevronDown size={16}/></button>{open?<div className="admin-topbar__menu-popover"><Link href="/admin/settings"><UserCircle2 size={16}/>Mon profil</Link><Link href="/admin/settings/security"><ShieldCheck size={16}/>Sécurité</Link><button type="button" onClick={()=>void logout()}><LogOut size={16}/>Déconnexion</button></div>:null}</div></div></header>}
