import { z } from "zod";
import type { CollectionSummary, Notification, Page } from "@/features/engagement/types";
const uuid = z.string().uuid();
const collection = z.object({ id: uuid, title: z.string().min(1).max(160), description: z.string().nullable(), isPublic: z.boolean(), createdAt: z.string().datetime({ offset: true }), updatedAt: z.string().datetime({ offset: true }), places: z.array(z.unknown()).nullable().optional(), items: z.array(z.unknown()).nullable().optional() });
const page = z.object({ content: z.array(collection), number: z.number().int().nonnegative(), size: z.number().int().positive(), totalElements: z.number().int().nonnegative(), totalPages: z.number().int().nonnegative(), last: z.boolean() });
const notification = z.object({ id: uuid, eventType: z.string().min(1), title: z.string(), body: z.string(), dataJson: z.string(), createdAt: z.string().datetime({ offset: true }), readAt: z.string().datetime({ offset: true }).nullable() });
export function mapCollectionPage(input: unknown): Page<CollectionSummary> { const value = page.parse(input); return { items: value.content.map((item) => ({ id: item.id, title: item.title, description: item.description, isPublic: item.isPublic, placeCount: item.items?.length ?? item.places?.length ?? 0, updatedAt: item.updatedAt })), page: value.number, size: value.size, totalElements: value.totalElements, totalPages: value.totalPages, last: value.last }; }
export function mapNotifications(input: unknown): Page<Notification> { const slice = z.object({ items: z.array(notification), page: z.number().int().optional(), size: z.number().int().optional(), total: z.number().int().optional() }).parse(input); return { items: slice.items.map((item) => { let data: Record<string, unknown> = {}; try { const parsed: unknown = JSON.parse(item.dataJson); if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) data = parsed as Record<string, unknown>; } catch {} return { id: item.id, eventType: item.eventType, title: item.title, body: item.body, data, createdAt: item.createdAt, readAt: item.readAt }; }), page: slice.page ?? 0, size: slice.size ?? slice.items.length, totalElements: slice.total ?? slice.items.length, totalPages: 1, last: true }; }
export function notificationHref(notification: Notification) { const type = typeof notification.data.targetType === "string" ? notification.data.targetType.toLowerCase() : ""; const id = typeof notification.data.targetId === "string" ? notification.data.targetId : ""; if (!uuid.safeParse(id).success) return null; if (type === "post") return `/posts/${id}`; if (type === "event") return `/events/${id}`; if (type === "place") return `/places/${id}`; if (type === "profile") return `/users/${id}`; return null; }
