"use client";

import Link from "next/link";
import Image from "next/image";
import { useRouter, useSearchParams } from "next/navigation";
import type { Route } from "next";
import { useMutation, useQuery } from "@tanstack/react-query";
import { MessageCircle, Palette, Search, Store } from "lucide-react";
import { Button, EmptyState, ErrorState, Skeleton } from "@/components/public/ui";
import { cultureMarketApi } from "@/features/culture-market/api";
import type { Artisan, ArtworkSummary } from "@/features/culture-market/types";
import { useProtectedAction } from "@/features/user-auth/protected-action-context";
import { userAuthFetch } from "@/lib/user-auth/client";

function ArtisanCard({ artisan }: { artisan: Artisan }) { return <article className="yy-market-card"><span className="yy-market-card__visual"><Store aria-hidden="true" /></span><div><h2><Link href={`/artisans/${artisan.id}` as Route}>{artisan.displayName}</Link></h2><p>{artisan.craftDescription}</p><div className="yy-market-tags">{artisan.specialties.map((item) => <span key={item.id}>{item.name}</span>)}</div></div></article>; }
function ArtworkCard({ artwork }: { artwork: ArtworkSummary }) { return <article className="yy-market-card"><span className="yy-market-card__visual"><Palette aria-hidden="true" /></span><div><h2><Link href={`/artworks/${artwork.id}` as Route}>{artwork.title}</Link></h2>{artwork.shortDescription ? <p>{artwork.shortDescription}</p> : null}<small>{artwork.yearCreated ?? artwork.countryCode} · {artwork.availabilityStatus.replaceAll("_", " ")}</small><Link className="yy-market-owner" href={`/artisans/${artwork.artisanId}` as Route}>Voir l’artisan</Link></div></article>; }
function Pager({ page, hasNext, href }: { page: number; hasNext: boolean; href: (page: number) => string }) { return <nav className="yy-market-pager" aria-label="Pagination">{page > 0 ? <Link href={href(page - 1) as Route}>Précédent</Link> : <span />}{hasNext ? <Link href={href(page + 1) as Route}>Suivant</Link> : null}</nav>; }

export function ArtisansPage() { const params = useSearchParams(); const queryString = params.toString(); const query = useQuery({ queryKey: ["public", "artisans", queryString], queryFn: () => cultureMarketApi.artisans(queryString), retry: false }); const specialties = useQuery({ queryKey: ["public", "artisan-specialties"], queryFn: cultureMarketApi.specialties, staleTime: 300_000 }); const page = Number(params.get("page") ?? 0); const href = (next: number) => { const value = new URLSearchParams(queryString); value.set("page", String(next)); return `/artisans?${value}`; }; return <section className="yy-market"><header><p className="yy-kicker">Savoir-faire</p><h1>Artisans</h1><p>Découvrez les profils vérifiés et leurs pratiques réelles.</p></header><form className="yy-market-filters"><label><span>Rechercher</span><span className="yy-market-input"><Search aria-hidden="true" /><input name="search" defaultValue={params.get("search") ?? ""} maxLength={120} /></span></label><label><span>Spécialité</span><select name="specialtyId" defaultValue={params.get("specialtyId") ?? ""}><option value="">Toutes</option>{specialties.data?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><input type="hidden" name="page" value="0" /><Button type="submit">Filtrer</Button></form>{query.isPending ? <div className="yy-market-grid"><Skeleton /><Skeleton /></div> : query.isError ? <ErrorState title="Artisans indisponibles" message="Le catalogue des artisans ne peut pas être chargé." /> : query.data.items.length ? <><div className="yy-market-grid">{query.data.items.map((artisan) => <ArtisanCard key={artisan.id} artisan={artisan} />)}</div><Pager page={page} hasNext={query.data.hasNext} href={href} /></> : <EmptyState title="Aucun artisan" message="Aucun profil vérifié ne correspond à ces critères." />}</section>; }
export function ArtworksPage() { const params = useSearchParams(); const queryString = params.toString(); const query = useQuery({ queryKey: ["public", "artworks", queryString], queryFn: () => cultureMarketApi.artworks(queryString), retry: false }); const page = Number(params.get("page") ?? 0); const href = (next: number) => { const value = new URLSearchParams(queryString); value.set("page", String(next)); return `/artworks?${value}`; }; return <section className="yy-market"><header><p className="yy-kicker">Créations</p><h1>Œuvres</h1><p>Explorez les œuvres publiées par les artisans Yeyamo.</p></header><form className="yy-market-filters"><label><span>Rechercher</span><span className="yy-market-input"><Search aria-hidden="true" /><input name="search" defaultValue={params.get("search") ?? ""} maxLength={120} /></span></label><label><span>Disponibilité</span><select name="availability" defaultValue={params.get("availability") ?? ""}><option value="">Toutes</option><option value="DISPLAY_ONLY">Exposition</option><option value="AVAILABLE">Disponible</option><option value="ON_ORDER">Sur commande</option><option value="RESERVED">Réservée</option><option value="SOLD">Vendue</option></select></label><input type="hidden" name="page" value="0" /><Button type="submit">Filtrer</Button></form>{query.isPending ? <div className="yy-market-grid"><Skeleton /><Skeleton /></div> : query.isError ? <ErrorState title="Œuvres indisponibles" message="Le catalogue des œuvres ne peut pas être chargé." /> : query.data.items.length ? <><div className="yy-market-grid">{query.data.items.map((artwork) => <ArtworkCard key={artwork.id} artwork={artwork} />)}</div><Pager page={page} hasNext={query.data.hasNext} href={href} /></> : <EmptyState title="Aucune œuvre" message="Aucune œuvre publiée ne correspond à ces critères." />}</section>; }
export function ArtisanDetailPage({ id }: { id: string }) { const router = useRouter(); const protectedAction = useProtectedAction(); const artisan = useQuery({ queryKey: ["public", "artisan", id], queryFn: () => cultureMarketApi.artisan(id), retry: false }); const works = useQuery({ queryKey: ["public", "artworks", "artisan", id], queryFn: () => cultureMarketApi.artworks(`artisanId=${encodeURIComponent(id)}&size=12`), retry: false }); const contact = useMutation({ mutationFn: () => userAuthFetch<{ id: string }>(`/api/user/artisans/${id}/contact`, { method: "POST" }), onSuccess: (conversation) => router.push(`/messages/${conversation.id}` as Route) }); if (artisan.isPending) return <div className="yy-detail yy-detail-skeleton"><Skeleton /><Skeleton /></div>; if (artisan.isError) return <ErrorState title="Artisan indisponible" message="Ce profil vérifié est introuvable." />; const value = artisan.data; return <article className="yy-detail"><header><p className="yy-kicker">Artisan vérifié</p><h1>{value.displayName}</h1><p>{value.craftDescription}</p></header><div className="yy-detail-layout"><div><section><h2>Son histoire</h2><p>{value.story}</p></section><section><h2>Portfolio</h2>{works.isPending ? <Skeleton /> : works.data?.items.length ? <div className="yy-market-grid">{works.data.items.map((work) => <ArtworkCard key={work.id} artwork={work} />)}</div> : <p>Aucune œuvre publiée pour le moment.</p>}</section></div><aside><p>{[value.cityId, value.countryCode].filter(Boolean).join(", ")}</p><div className="yy-market-tags">{value.specialties.map((item) => <span key={item.id}>{item.name}</span>)}</div><div className="yy-detail-actions"><Button loading={contact.isPending} onClick={() => protectedAction({ reason: `Connectez-vous pour contacter ${value.displayName}`, level: "L1", run: () => contact.mutate() })}><MessageCircle aria-hidden="true" />Contacter</Button><Link className="yy-button yy-detail-action" href={`/artworks?artisanId=${id}` as Route}>Voir toutes les œuvres</Link></div>{contact.isError ? <p role="alert">La conversation ne peut pas être ouverte actuellement.</p> : null}</aside></div></article>; }
export function ArtworkDetailPage({ id }: { id: string }) { const artwork = useQuery({ queryKey: ["public", "artwork", id], queryFn: () => cultureMarketApi.artwork(id), retry: false }); const artisan = useQuery({ queryKey: ["public", "artwork-artisan", artwork.data?.artisanId], queryFn: () => cultureMarketApi.artisan(artwork.data!.artisanId), enabled: Boolean(artwork.data?.artisanId), retry: false }); if (artwork.isPending) return <div className="yy-detail yy-detail-skeleton"><Skeleton /><Skeleton /></div>; if (artwork.isError) return <ErrorState title="Œuvre indisponible" message="Cette œuvre publiée est introuvable." />; const value = artwork.data; return <article className="yy-detail"><header><p className="yy-kicker">Œuvre</p><h1>{value.title}</h1>{value.shortDescription ? <p>{value.shortDescription}</p> : null}</header>{value.media.length ? <div className="yy-detail-media">{value.media.map((media) => <Image key={media.id} src={media.url} alt="" width={900} height={700} unoptimized />)}</div> : <div className="yy-market-artwork-fallback"><Palette aria-hidden="true" /><span>Aucun média public</span></div>}<div className="yy-detail-layout"><div>{value.story ? <section><h2>À propos</h2><p>{value.story}</p></section> : null}<section><h2>Caractéristiques</h2><p>{[value.yearCreated, value.editionType.replaceAll("_", " "), value.culturalCommunity].filter(Boolean).join(" · ")}</p></section></div><aside><p>{value.availabilityStatus.replaceAll("_", " ")}</p><p>{value.authenticityStatus.replaceAll("_", " ")}</p><div className="yy-detail-actions"><Link className="yy-button yy-detail-action" href={`/artisans/${value.artisanId}` as Route}>{artisan.data ? `Voir ${artisan.data.displayName}` : "Voir l’artisan"}</Link></div><p className="yy-market-note">Aucun achat ni favori n’est proposé sans contrat backend certifié.</p></aside></div></article>; }
