"use client";
import Link from "next/link";
import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useRouter } from "next/navigation";
import { catalogApi } from "@/features/catalog/api/catalog-api";
import { AdminEmptyState, AdminErrorState, AdminPageHeader, AdminSkeleton, AdminStatCard } from "@/components/admin/ui/admin-foundation";
import { queryKeys } from "@/lib/query/query-keys";
export function ImportsPage(){return <div className="admin-feature"><AdminPageHeader title="Imports catalogue"/><AdminEmptyState title="Liste non exposée" description="ingestion-service expose uniquement POST /imports et GET /imports/{id}. Aucune liste, annulation ou relance n’est disponible." action={<Link className="admin-button" href="/admin/catalog/imports/new">Nouvel import</Link>}/></div>}
export function ImportForm(){const router=useRouter();const[sourceType,setType]=useState("MANUAL");const[reference,setReference]=useState("");const[payload,setPayload]=useState("");const mutation=useMutation({mutationFn:()=>catalogApi.submitImport({sourceType,sourceReference:reference||undefined,payload:payload||undefined}),onSuccess:(job)=>router.push(`/admin/catalog/imports/${job.id}` as never)});return <div className="admin-feature"><AdminPageHeader title="Nouvel import" description="Le backend accepte un payload texte/JSON, pas un upload multipart."/><form className="admin-form" onSubmit={(event)=>{event.preventDefault();mutation.mutate()}}><label>Source type<input value={sourceType} onChange={(event)=>setType(event.target.value)}/></label><label>Référence<input value={reference} onChange={(event)=>setReference(event.target.value)}/></label><label>Payload<textarea rows={15} value={payload} onChange={(event)=>setPayload(event.target.value)}/></label>{mutation.error?<AdminErrorState error={mutation.error}/>:null}<button className="admin-button">Soumettre</button></form></div>}
export function ImportDetail({id}:{id:string}){const query=useQuery({queryKey:queryKeys.catalog.detail(`import-${id}`),queryFn:()=>catalogApi.importJob(id),refetchInterval:(current)=>current.state.data?.status==="RUNNING"?5000:false});if(query.isLoading)return <AdminSkeleton/>;if(query.error)return <AdminErrorState error={query.error}/>;const job=query.data!;return <div className="admin-feature"><AdminPageHeader title={`Import ${job.id}`} description={job.status}/><div className="admin-kpi-grid"><AdminStatCard label="Total" value={job.totalRecords}/><AdminStatCard label="Acceptées" value={job.acceptedRecords}/><AdminStatCard label="Rejetées" value={job.rejectedRecords}/><AdminStatCard label="Doublons" value={job.duplicateRecords}/></div>{job.errorMessage?<AdminErrorState error={job.errorMessage}/>:null}</div>}
