"use client";

import { Search, X } from "lucide-react";
import type { KeyboardEvent, ReactNode } from "react";
import { useEffect, useId, useRef } from "react";
import { Can, type AccessRequirement } from "@/features/auth/permissions";
import { cn } from "@/lib/utils";

export function AdminPageHeader({ title, description, actions, breadcrumb }: { title: string; description?: string; actions?: ReactNode; breadcrumb?: ReactNode }) { return <header className="admin-page-header"><div>{breadcrumb}<h2>{title}</h2>{description ? <p>{description}</p> : null}</div>{actions ? <div className="admin-page-header__actions">{actions}</div> : null}</header>; }
export function AdminBreadcrumb({ items }: { items: { label: string; href?: string }[] }) { return <nav className="admin-breadcrumb" aria-label="Fil d’Ariane"><ol>{items.map((item) => <li key={`${item.href ?? "current"}-${item.label}`}>{item.href ? <a href={item.href}>{item.label}</a> : <span aria-current="page">{item.label}</span>}</li>)}</ol></nav>; }
export function AdminSearchInput({ value, onChange, placeholder = "Rechercher…", label = "Rechercher" }: { value: string; onChange: (value: string) => void; placeholder?: string; label?: string }) { return <label className="admin-search-input"><span className="admin-visually-hidden">{label}</span><Search size={17} aria-hidden="true"/><input type="search" value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} aria-label={label}/></label>; }
export function AdminFilters({ children, onReset }: { children: ReactNode; onReset?: () => void }) { return <section className="admin-filters" aria-label="Filtres">{children}{onReset ? <button type="button" className="admin-button admin-button--secondary" onClick={onReset}>Réinitialiser</button> : null}</section>; }
export function AdminPagination({ page, size, total, onPageChange, onSizeChange }: { page: number; size: number; total: number; onPageChange: (page: number) => void; onSizeChange?: (size: number) => void }) { const pages = Math.max(1, Math.ceil(total / size)); const safePage = Math.min(page, pages - 1); return <nav className="admin-pagination" aria-label="Pagination"><span className="admin-pagination__summary">{total.toLocaleString("fr-FR")} résultat{total > 1 ? "s" : ""}</span><button type="button" disabled={safePage <= 0} onClick={() => onPageChange(safePage - 1)}>Précédent</button><span aria-live="polite">Page {safePage + 1} sur {pages}</span>{onSizeChange ? <label><span className="admin-visually-hidden">Résultats par page</span><select aria-label="Résultats par page" value={size} onChange={(event) => onSizeChange(Number(event.target.value))}>{[10,20,50,100].map((value) => <option key={value} value={value}>{value} / page</option>)}</select></label> : null}<button type="button" disabled={safePage + 1 >= pages} onClick={() => onPageChange(safePage + 1)}>Suivant</button></nav>; }
export function AdminSort({ value, options, onChange }: { value?: string; options: { value: string; label: string }[]; onChange: (value: string) => void }) { return <select aria-label="Trier" value={value ?? ""} onChange={(event) => onChange(event.target.value)}><option value="">Tri par défaut</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select>; }

const statusAliases: Record<string, string> = { enabled: "active", disabled: "suspended", validated: "approved", accepted: "approved", denied: "rejected", canceled: "cancelled", paid: "completed", success: "completed", error: "failed", inactive: "suspended", open: "pending", processing: "pending" };
export function normalizeAdminStatus(status: string) { const normalized = status.trim().toLowerCase().replace(/[\s_-]+/g, "-"); return statusAliases[normalized] ?? normalized; }
export function AdminStatusBadge({ status, label }: { status: string; label?: string }) { const normalized = normalizeAdminStatus(status); return <span className="admin-status-badge" data-status={normalized} title={label ?? status}>{label ?? status}</span>; }
export function AdminEmptyState({ title = "Aucune donnée", description, action }: { title?: string; description?: string; action?: ReactNode }) { return <div className="admin-state" role="status"><strong>{title}</strong>{description ? <p>{description}</p> : null}{action}</div>; }
export function AdminErrorState({ error, onRetry }: { error: Error | string; onRetry?: () => void }) { const message = typeof error === "string" ? error : error.message; const correlationId = typeof error === "object" && "correlationId" in error ? String(error.correlationId ?? "") : ""; return <div className="admin-state admin-state--error" role="alert"><strong>Une erreur est survenue</strong><p>{message}</p>{correlationId ? <small>Correlation ID : {correlationId}</small> : null}{onRetry ? <button type="button" onClick={onRetry}>Réessayer</button> : null}</div>; }
export function AdminSkeleton({ rows = 4 }: { rows?: number }) { return <div className="admin-skeleton" role="status" aria-live="polite" aria-busy="true"><span className="admin-visually-hidden">Chargement en cours</span>{Array.from({ length: rows }, (_, index) => <span aria-hidden="true" key={index}/>)}</div>; }
export function AdminTabs({ tabs, active, onChange }: { tabs: { id: string; label: string }[]; active: string; onChange: (id: string) => void }) { const onKeyDown = (event: KeyboardEvent<HTMLDivElement>) => { if (!['ArrowLeft','ArrowRight','Home','End'].includes(event.key)) return; event.preventDefault(); const index = tabs.findIndex((tab) => tab.id === active); const next = event.key === 'Home' ? 0 : event.key === 'End' ? tabs.length - 1 : (index + (event.key === 'ArrowRight' ? 1 : -1) + tabs.length) % tabs.length; onChange(tabs[next].id); }; return <div className="admin-tabs" role="tablist" onKeyDown={onKeyDown}>{tabs.map((tab) => <button type="button" role="tab" tabIndex={active === tab.id ? 0 : -1} aria-selected={active === tab.id} key={tab.id} onClick={() => onChange(tab.id)}>{tab.label}</button>)}</div>; }
export function AdminTimeline({ items }: { items: { id: string; title: string; description?: string | null; date?: string }[] }) { return <ol className="admin-timeline">{items.map((item) => <li key={item.id}><strong>{item.title}</strong>{item.description ? <p>{item.description}</p> : null}{item.date ? <time dateTime={item.date}>{item.date}</time> : null}</li>)}</ol>; }
export function AdminStatCard({ label, value, detail }: { label: string; value: ReactNode; detail?: ReactNode }) { return <article className="admin-section-card admin-stat-card"><p>{label}</p><strong>{value}</strong>{detail}</article>; }
export const AdminMetricCard = AdminStatCard;
export function AdminPermissionGuard({ children, ...requirement }: AccessRequirement & { children: ReactNode }) { return <Can {...requirement}>{children}</Can>; }
export function AdminDateRangePicker({ from, to, onChange }: { from?: string; to?: string; onChange: (range: { from?: string; to?: string }) => void }) { return <fieldset className="admin-date-range"><legend className="admin-visually-hidden">Période</legend><label><span className="admin-visually-hidden">Date de début</span><input aria-label="Date de début" type="date" value={from ?? ""} onChange={(event) => onChange({ from: event.target.value || undefined, to })}/></label><label><span className="admin-visually-hidden">Date de fin</span><input aria-label="Date de fin" type="date" value={to ?? ""} onChange={(event) => onChange({ from, to: event.target.value || undefined })}/></label></fieldset>; }

export function AdminDialog({ open, title, children, onClose, footer, className }: { open: boolean; title: string; children: ReactNode; onClose: () => void; footer?: ReactNode; className?: string }) { const titleId = useId(); const dialogRef = useRef<HTMLElement>(null); const previousFocus = useRef<HTMLElement | null>(null); useEffect(() => { if (!open) return; previousFocus.current = document.activeElement as HTMLElement; const dialog = dialogRef.current; dialog?.querySelector<HTMLElement>('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])')?.focus(); const onKeyDown = (event: globalThis.KeyboardEvent) => { if (event.key === 'Escape') onClose(); if (event.key !== 'Tab' || !dialog) return; const focusable = [...dialog.querySelectorAll<HTMLElement>('button:not(:disabled), [href], input:not(:disabled), select:not(:disabled), textarea:not(:disabled), [tabindex]:not([tabindex="-1"])')]; if (!focusable.length) return; const first = focusable[0]; const last = focusable[focusable.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; document.addEventListener('keydown', onKeyDown); document.body.style.overflow = 'hidden'; return () => { document.removeEventListener('keydown', onKeyDown); document.body.style.overflow = ''; previousFocus.current?.focus(); }; }, [open, onClose]); if (!open) return null; return <div className="admin-dialog-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section ref={dialogRef} className={cn("admin-dialog", className)} role="dialog" aria-modal="true" aria-labelledby={titleId}><header><h3 id={titleId}>{title}</h3><button type="button" className="admin-icon-button" onClick={onClose} aria-label="Fermer"><X size={18} aria-hidden="true"/></button></header><div className="admin-dialog__body">{children}</div>{footer ? <footer>{footer}</footer> : null}</section></div>; }
export function AdminConfirmDialog({ open, title, message, confirmLabel = "Confirmer", destructive, busy, onConfirm, onClose }: { open: boolean; title: string; message: string; confirmLabel?: string; destructive?: boolean; busy?: boolean; onConfirm: () => void; onClose: () => void }) { return <AdminDialog open={open} title={title} onClose={onClose} footer={<><button type="button" className="admin-button admin-button--secondary" onClick={onClose}>Annuler</button><button type="button" className="admin-button" data-destructive={destructive} disabled={busy} aria-busy={busy} onClick={onConfirm}>{busy ? "Traitement…" : confirmLabel}</button></>}>{message}</AdminDialog>; }
export const AdminDetailDrawer = AdminDialog;
export const AdminFormDialog = AdminDialog;
