"use client";
import { MoreVertical } from "lucide-react";
import { createPortal } from "react-dom";
import { type CSSProperties, type KeyboardEvent, type ReactNode, useEffect, useId, useRef, useState } from "react";

export function RowActionsMenu({ children, triggerLabel }: { children: ReactNode; triggerLabel: string }) {
  const [open, setOpen] = useState(false); const [position, setPosition] = useState<CSSProperties>(); const rootRef = useRef<HTMLDivElement>(null); const triggerRef = useRef<HTMLButtonElement>(null); const menuRef = useRef<HTMLDivElement>(null); const menuId = useId();
  useEffect(() => { if (!open) return; const rect = triggerRef.current?.getBoundingClientRect(); if (rect) setPosition({ position: "fixed", top: rect.bottom + 4, right: Math.max(8, window.innerWidth - rect.right), zIndex: 100 }); const frame = requestAnimationFrame(() => { const items = menuRef.current?.querySelectorAll<HTMLElement>("a,button") ?? []; items.forEach((item) => { item.setAttribute("role", "menuitem"); if (item.matches(":disabled")) item.setAttribute("aria-disabled", "true"); }); [...items].find((item) => !item.matches(":disabled"))?.focus(); }); const close = (event: MouseEvent | globalThis.KeyboardEvent) => { if (event instanceof globalThis.KeyboardEvent) { if (event.key === "Escape") { setOpen(false); triggerRef.current?.focus(); } } else if (!rootRef.current?.contains(event.target as Node) && !menuRef.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener("mousedown", close); document.addEventListener("keydown", close); return () => { cancelAnimationFrame(frame); document.removeEventListener("mousedown", close); document.removeEventListener("keydown", close); }; }, [open]);
  const handleKeyDown = (event: KeyboardEvent<HTMLDivElement>) => { if (event.key !== "ArrowDown" && event.key !== "ArrowUp") return; const items = [...(menuRef.current?.querySelectorAll<HTMLElement>("a,button:not(:disabled)") ?? [])]; if (!items.length) return; event.preventDefault(); const current = items.indexOf(document.activeElement as HTMLElement); const delta = event.key === "ArrowDown" ? 1 : -1; items[(current + delta + items.length) % items.length]?.focus(); };
  return <div className="admin-row-menu" ref={rootRef}><button ref={triggerRef} type="button" className="admin-row-menu__trigger" aria-label={triggerLabel} aria-haspopup="menu" aria-expanded={open} aria-controls={menuId} onClick={() => setOpen((value) => !value)}><MoreVertical size={18} aria-hidden="true" /></button>{open && position ? createPortal(<div id={menuId} ref={menuRef} style={position} className="admin-row-menu__popover" role="menu" onKeyDown={handleKeyDown} onClickCapture={(event) => { if ((event.target as HTMLElement).closest("a,button")) setOpen(false); }}>{children}</div>, document.body) : null}</div>;
}
