import { z } from "zod";
import { businessTypes, type PartnerBookingPage, type PartnerProfile, type PartnerStatusView } from "@/features/partner-portal/types";

const instant = z.string().datetime({ offset: true });
const profileSchema = z.object({ id: z.string().uuid(), legalName: z.string(), tradeName: z.string().nullable(), businessType: z.enum(businessTypes), registrationNumber: z.string().nullable(), taxId: z.string().nullable(), contactEmail: z.string().email(), contactPhone: z.string().nullable(), websiteUrl: z.string().nullable(), description: z.string().nullable(), primaryCountryCode: z.string().nullable(), operatingCountries: z.array(z.string()), status: z.enum(["DRAFT", "SUBMITTED", "UNDER_REVIEW", "NEEDS_INFO", "REQUIRES_CHANGES", "APPROVED", "REJECTED", "SUSPENDED", "DELETED"]), reviewComment: z.string().nullable(), riskScore: z.number().nullable(), submittedAt: instant.nullable(), verifiedAt: instant.nullable(), createdAt: instant, updatedAt: instant });
export function mapPartnerProfile(input: unknown): PartnerProfile { const value = profileSchema.parse(input); return { id: value.id, legalName: value.legalName, tradeName: value.tradeName, businessType: value.businessType, registrationNumber: value.registrationNumber, taxId: value.taxId, contactEmail: value.contactEmail, contactPhone: value.contactPhone, websiteUrl: value.websiteUrl, description: value.description, primaryCountryCode: value.primaryCountryCode, operatingCountries: value.operatingCountries, status: value.status, reviewComment: value.reviewComment, submittedAt: value.submittedAt, verifiedAt: value.verifiedAt, createdAt: value.createdAt, updatedAt: value.updatedAt }; }
export function partnerStatus(profile: PartnerProfile | null): PartnerStatusView { if (!profile) return { state: "NOT_PARTNER", profile: null, canEdit: false, canSubmit: false, canAccessDashboard: false }; const editable = ["DRAFT", "NEEDS_INFO", "REQUIRES_CHANGES", "REJECTED"].includes(profile.status); const state = profile.status === "APPROVED" ? "ACTIVE" : profile.status === "SUSPENDED" ? "SUSPENDED" : profile.status === "REJECTED" ? "REJECTED" : profile.status === "DRAFT" || profile.status === "NEEDS_INFO" || profile.status === "REQUIRES_CHANGES" ? "APPLICATION_DRAFT" : "APPLICATION_PENDING"; return { state, profile, canEdit: editable, canSubmit: editable, canAccessDashboard: profile.status === "APPROVED" }; }
const booking = z.object({ id: z.string().uuid(), reference: z.string(), userId: z.string(), activityId: z.string(), slotId: z.string().uuid(), quantity: z.number().int().positive(), unitPrice: z.number(), totalAmount: z.number(), currency: z.string().length(3), countryCode: z.string().nullable(), status: z.string(), paymentStatus: z.string(), cancellationReason: z.string().nullable(), createdAt: instant, confirmedAt: instant.nullable(), cancelledAt: instant.nullable(), completedAt: instant.nullable() });
export function mapPartnerBookings(input: unknown): PartnerBookingPage { const value = z.object({ content: z.array(booking), number: z.number().int().nonnegative(), size: z.number().int().positive(), last: z.boolean() }).parse(input); return { page: value.number, size: value.size, hasNext: !value.last, items: value.content.map((item) => ({ id: item.id, reference: item.reference, activityId: item.activityId, slotId: item.slotId, quantity: item.quantity, totalAmount: item.totalAmount, currency: item.currency, countryCode: item.countryCode, status: item.status, paymentStatus: item.paymentStatus, cancellationReason: item.cancellationReason, createdAt: item.createdAt, confirmedAt: item.confirmedAt, cancelledAt: item.cancelledAt, completedAt: item.completedAt })) }; }
